# Generated by Django 3.1.7 on 2021-03-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('desc', models.CharField(max_length=299)),
                ('price', models.CharField(max_length=4)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
    ]
